
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_BY_SIZE_PRICE_RANGE 	= "FILTER_PRODUCTS_BY_SIZE_PRICE_RANGE";
export const FILTER_PRODUCTS_BY_MODEL   = "FILTER_PRODUCTS_BY_MODEL";
export const FILTER_PRODUCTS_BY_BRAND   = "FILTER_PRODUCTS_BY_BRAND";
export const UPDATE_FILTERED_PRODUCTS   = "UPDATE_FILTERED_PRODUCTS";